---
title: "photo_model_eval"
author: "Anonymous"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Global variables
PATH <- "SET PATH HERE"
META_LIST <- list(COUNTRIES=c("Nigeria", "Zambia", "Zambia", "Zimbabwe"),
                  YEARS=c(2022, 2023, 2024, 2024),
                  FNAMES=paste0(PATH, c("nigeria_2022_filtered.csv", 
                                        "zambia_2023_filtered.csv",
                                        "zambia_2024_filtered.csv", 
                                        "zimbabwe_2024_filtered.csv")),
                  SHP_PATHS=paste0(PATH, c("nga_admbnda_adm1_osgof_20190417.shp", 
                                           "zmb_admbnda_adm1_dmmu_20201124.shp",
                                           "zmb_admbnda_adm1_dmmu_20201124.shp", 
                                           "zwe_admbnda_adm1_zimstat_ocha_20180911.shp")))
N_REP <- 10 # number of times to resample each zone; we average over the results for each zone to report final metrics
```

```{r}
# Check that all components of META_LIST have the same length
stopifnot(var(lengths(META_LIST)) == 0) 
m <- length(META_LIST$COUNTRIES)
```

```{r}
# Imports
library(tidyverse)
library(glmnet)
library(readxl)
library(gridExtra)
library(sf)
source(paste0(PATH, "helpers.R"))
```

## Read in data and perform initial preprocessing

```{r}
# Reads in data file containing (longitude, latitude) coordinates
# along with shapefile of study region boundaries, with names of regions in
# column name specified by 'study_region_col'
get_data_with_study_region <- function(data_path, shp_path, study_region_col) {
  data <- read_csv(data_path)
  shp <- st_read(shp_path)
  if (!(all(c("longitude", "latitude") %in% names(data)))) {
    stop("data does not have both columns 'longitude' and 'latitude'")
  }
  if (!(study_region_col %in% names(shp))) {
    stop(paste("shapefile does not contain column", study_region_col))
  }
  crs <- st_crs(shp)$epsg
  query_points <- st_as_sf(data, coords=c("longitude", "latitude"), crs=crs)
  inds <- apply(X=st_intersects(query_points, shp, sparse=FALSE), MARGIN=1, 
                FUN=function(v) match(TRUE, v))
  return(mutate(data, study_region=shp[[study_region_col]][inds]))
}
```

```{r}
# Fuzz the study region so that all points in the same zone are in the same study region
# Assign zone to study region by plurality membership of fields
zone_fuzz_study_region <- function(df) {
  df_by_zone <- split(df, df$zone)
  zone_study_regions <- sapply(df_by_zone, function(df) names(sort(table(df$study_region), decreasing=TRUE))[1])
  n_zone <- length(df_by_zone)
  fuzzed_df_by_zone <- vector("list", n_zone)
  for (i in 1:n_zone) {
    curr_df <- df_by_zone[[i]]
    curr_df$study_region <- zone_study_regions[i]
    fuzzed_df_by_zone[[i]] <- curr_df
  }
  return(do.call(rbind, fuzzed_df_by_zone))
}
```

```{r}
# Read in data, add study region boundaries, and select relevant columns
files <- lapply(1:m, function(i) {
  dat <- get_data_with_study_region(data_path=META_LIST$FNAMES[i],
                                    shp_path=META_LIST$SHP_PATHS[i],
                                    study_region_col="ADM1_EN")
  return(zone_fuzz_study_region(dat) %>%
          rename(year=data_collection_year, y=Avg_yield_mt_ha) %>%
          dplyr::select(cce_id, year, crop, latitude, longitude, y, zone, 
                        starts_with("pred"), contains("fold"), study_region) %>%
          mutate(latlon=latitude * longitude,
                 lonsq=longitude^2,
                 latsq=latitude^2))
})
files[[1]]
```

## Data processing

```{r}
# Filter data only to zones with at least min_zone_size fields
filter_zones <- function(df, min_zone_size=20) {
  zone_summary_df <- df %>%
    group_by(zone) %>%
    summarise(n_zone=n())
  good_zones <- zone_summary_df$zone[zone_summary_df$n_zone >= min_zone_size]
  filter_df <- filter(df, zone %in% good_zones)
  return(filter_df)
}
```

```{r}
# Check that no observation has more than one prediction and add pred column
add_pred_col <- function(df, filter_NA=FALSE) {
  df <- df %>%
    rowwise() %>%
    mutate(n_preds = sum(!is.na(c_across(starts_with("pred_fold")))),
           pred=pmax(0, mean(c_across(starts_with("pred_fold")), na.rm=TRUE))) %>%
    ungroup()
  if (filter_NA) {
    df <- filter(df, n_preds >= 1)
  }
  stopifnot(max(df$n_preds) == 1)
  return(df)
}
```

```{r}
# Filter out small zones and add pred column
dfs <- lapply(files, function(df) add_pred_col(filter_zones(df), filter_NA=TRUE))
```

## R^2 evaluation

```{r}
# Cross-zone R^2 (see Table 2)
sapply(dfs, function(df) with(df, cor(pred, y)^2))
```


```{r}
# Estimate zone average R^2 of photo predictions for each (country, year)
r_sq_eval <- function(df) {
  grp_df <- df %>%
    group_by(zone)
  split_df <- group_split(grp_df)
  zone_r_sq <- sapply(split_df, function(df) cor(df$pred, df$y)^2)
  zone_r_sq[is.na(zone_r_sq)] <- 0 # if pred or y column is constant
  zone_size_df <- data.frame(size=sapply(split_df, nrow),
                             zone=group_keys(grp_df),
                             r2=zone_r_sq)
  return(zone_size_df)
}
```

```{r}
r_sq_list <- lapply(dfs, r_sq_eval)
r_sq_list_names <- with(META_LIST, paste(COUNTRIES, YEARS, sep=" "))
names(r_sq_list) <- r_sq_list_names
saveRDS(r_sq_list, paste0(PATH, "r_sq_list.rds"))
for (i in 1:m) {
  curr_r_sq_df <- r_sq_list[[i]]
  write_csv(curr_r_sq_df, file=paste0(PATH, "zone_r_sq_", r_sq_list_names[[i]], ".csv"))
}
```

```{r}
# Within-zone R^2 (see Table 2)
sapply(r_sq_list, function(df) mean(df$r2))
```

## PPI simulations

```{r}
run_fold_photo_sims <-  function(df, cov_names, K_cf, K_cv, R, boot_ci_type, 
                                 alpha, rectifier_scale, reg_method,
                                 boot_n_lbl_mult, boot_n_unlbl_mult, seed=NULL) {
  
  ## Separate data by (country, year)
  lbl <- split(df, df$study_region)
  unlbl <- lbl
  
  ## Run simulations
  out_temp <- run_sims(lbl_by_study_region=lbl, 
                       unlbl_by_study_region=unlbl, 
                       cov_names=cov_names, 
                       yhat="pred", K_cf=K_cf, K_cv=K_cv, R=R, 
                       boot_ci_type=boot_ci_type, alpha=alpha,
                       rectifier_scale=rectifier_scale,
                       reg_method=reg_method, boot=TRUE,
                       boot_n_lbl_mult=boot_n_lbl_mult,
                       boot_n_unlbl_mult=boot_n_unlbl_mult,
                       seed=seed)
  
  ## Add true theta and zone sizes
  truth_df <- df %>%
    group_by(zone) %>%
    summarise(theta=mean(y), size=n())
  sims_out <- lapply(out_temp, function(est_dfs) {
    lapply(est_dfs, function(res) {
      res %>%
        rownames_to_column(var="zone") %>%
        left_join(truth_df, by="zone")
    })
  })
  return(sims_out)
}
```

## Simulations with global pooling

```{r}
# bootstrap-t
global_outs_t <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=1000, boot_ci_type="student", alpha=0.05,
         rectifier_scale="global", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
global_outs_bca <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=1000, boot_ci_type="bca", alpha=0.05,
         rectifier_scale="global", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# Percentile
global_outs_pct <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=1000, boot_ci_type="percent", alpha=0.05,
         rectifier_scale="global", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```


```{r}
global_outs_bca_rf <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude"),
         K_cf=5, K_cv=5, R=1000, boot_ci_type="bca", alpha=0.05,
         rectifier_scale="global", reg_method="rf",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
global_outs_clt <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=NULL, boot_ci_type="none", alpha=0.05,
         rectifier_scale="global", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
saveRDS(global_outs_t, paste0(PATH, "global_outs_t.rds"))
saveRDS(global_outs_bca, paste0(PATH, "global_outs_bca.rds"))
saveRDS(global_outs_clt, paste0(PATH, "global_outs_clt.rds"))
saveRDS(global_outs_bca_rf, paste0(PATH, "global_outs_bca_rf.rds"))
saveRDS(global_outs_pct, paste0(PATH, "global_outs_pct.rds"))
```

## Study region control functions

```{r}
# bootstrap-t
study_region_outs_t <- lapply(1:N_REP, function(rep)
                       lapply(dfs, run_fold_photo_sims,
                              cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
                              K_cf=1, K_cv=5, R=1000, boot_ci_type="student", alpha=0.05,
                              rectifier_scale="study_region", reg_method="glmnet",
                              boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# BCA
study_region_outs_bca <- lapply(1:N_REP, function(rep)
                       lapply(dfs, run_fold_photo_sims,
                              cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
                              K_cf=1, K_cv=5, R=1000, boot_ci_type="bca", alpha=0.05,
                              rectifier_scale="study_region", reg_method="glmnet",
                              boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# BCA_rf
study_region_outs_bca_rf <- lapply(1:N_REP, function(rep)
                       lapply(dfs, run_fold_photo_sims,
                              cov_names=c("longitude", "latitude"),
                              K_cf=5, K_cv=5, R=1000, boot_ci_type="bca", alpha=0.05,
                              rectifier_scale="study_region", reg_method="rf",
                              boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# CLT
study_region_outs_clt <- lapply(1:N_REP, function(rep)
                        lapply(dfs, run_fold_photo_sims,
                               cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
                               K_cf=1, K_cv=5, R=NULL, boot_ci_type="none", alpha=0.05,
                               rectifier_scale="study_region", reg_method="glmnet",
                               boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# Percentile
study_region_outs_pct <- lapply(1:N_REP, function(rep)
                       lapply(dfs, run_fold_photo_sims,
                              cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
                              K_cf=1, K_cv=5, R=1000, boot_ci_type="percent", alpha=0.05,
                              rectifier_scale="study_region", reg_method="glmnet",
                              boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```


```{r}
saveRDS(study_region_outs_t, paste0(PATH, "study_region_outs_t.rds"))
saveRDS(study_region_outs_bca, paste0(PATH, "study_region_outs_bca.rds"))
saveRDS(study_region_outs_clt, paste0(PATH, "study_region_outs_clt.rds"))
saveRDS(study_region_outs_bca_rf, paste0(PATH, "study_region_outs_bca_rf.rds"))
saveRDS(study_region_outs_pct, paste0(PATH, "study_region_outs_pct.rds"))
```

## Zone level control function

```{r}
# bootstrap-T
zone_outs_t <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=1000, boot_ci_type="student", alpha=0.05,
         rectifier_scale="zone", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# BCA bootstrap
zone_outs_bca <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=1000, boot_ci_type="bca", alpha=0.05,
         rectifier_scale="zone", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# CLT intervals
zone_outs_clt <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=NULL, boot_ci_type="none", alpha=0.05,
         rectifier_scale="zone", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
# Percentile bootstrap
zone_outs_pct <- lapply(1:N_REP, function(rep)
  lapply(dfs, run_fold_photo_sims,
         cov_names=c("longitude", "latitude", "latlon", "lonsq", "latsq"),
         K_cf=1, K_cv=5, R=1000, boot_ci_type="percent", alpha=0.05,
         rectifier_scale="zone", reg_method="glmnet",
         boot_n_lbl_mult=1.001, boot_n_unlbl_mult=3.999, seed=rep)
)
```

```{r}
## save results
saveRDS(zone_outs_t, paste0(PATH, "zone_outs_t.rds"))
saveRDS(zone_outs_bca, paste0(PATH, "zone_outs_bca.rds"))
saveRDS(zone_outs_clt, paste0(PATH, "zone_outs_clt.rds"))
saveRDS(zone_outs_pct, paste0(PATH, "zone_outs_pct.rds"))
```













