name: crop_yield
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pandas
  - notebook
  - pillow
  - pyyaml
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - ipykernel
prefix:

